version: 2.1

commands:
  setup:
    steps:
      - run:
          name: Configure environment
          command: |
            apk update

      - checkout

      - run:
          name: Install dependencies
          command: |
            EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

            if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
                >&2 echo 'ERROR: Invalid installer checksum'
                rm composer-setup.php
                exit 1
            fi

            php composer-setup.php --quiet
            RESULT=$?
            rm composer-setup.php

            php composer.phar install --no-interaction --prefer-dist

  setup-pcov:
    steps:
      - run:
          name: Configure pcov
          command: |
            apk add autoconf gcc make musl-dev
            pecl install pcov
            docker-php-ext-enable pcov

  run-phpinsights:
    steps:
      - run:
          name: Run code quality analysis (PHP Insights)
          command: php -d memory-limit=-1 ./vendor/bin/phpinsights -v --no-interaction --min-quality=100 --min-complexity=50 --min-architecture=100 --min-style=100

  run-phpstan:
    steps:
      - run:
          name: Run static code analysis (PHPStan)
          command: php -d memory_limit=-1 ./vendor/bin/phpstan analyse --ansi

  run-pest:
    steps:
      - run:
          name: Run unit tests (Pest)
          command: php -d memory_limit=-1 ./vendor/bin/pest --stop-on-failure --min=100

  run-snyk:
    steps:
      - run:
          name: Run vulnerabilities tests (Snyk)
          command: |
            apk add npm
            npm install -g snyk
            snyk test --dev --org=auth0-sdks --project-name=auth0-PHP

jobs:
  phpinsights:
    working_directory: app
    parameters:
      php:
        type: string
    docker:
      - image: php:<< parameters.php >>-cli-alpine
    steps:
      - setup
      - run-phpinsights
  phpstan:
    working_directory: app
    parameters:
      php:
        type: string
    docker:
      - image: php:<< parameters.php >>-cli-alpine
    steps:
      - setup
      - run-phpstan
  semgrep:
    working_directory: app
    docker:
      - image: returntocorp/semgrep:latest
    steps:
      - checkout
      - run:
          name: Run static code analysis (Semgrep)
          command: semgrep --config auto
  pest:
    working_directory: app
    parameters:
      php:
        type: string
    docker:
      - image: php:<< parameters.php >>-cli-alpine
    steps:
      - setup
      - setup-pcov
      - run-pest
  snyk:
    working_directory: app
    parameters:
      php:
        type: string
    docker:
      - image: php:<< parameters.php >>-cli-alpine
    steps:
      - setup
      - run-snyk

workflows:
  test:
    jobs:
      - semgrep
      - phpinsights:
          matrix:
            parameters:
              php: ["8.0", "8.1"]
      - phpstan:
          matrix:
            parameters:
              php: ["8.0", "8.1"]
      - pest:
          matrix:
            parameters:
              php: ["8.0", "8.1"]
      - hold:
          type: approval
      - snyk:
          matrix:
            parameters:
              php: ["8.0", "8.1"]
          context:
            - snyk-env
          requires:
            - hold
