name: Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        working-directory: ./app

      - name: Composer normalize
        uses: docker://ergebnis/composer-normalize-action
        working-directory: ./app
